<div class="register_form container mt-5 mb-5 ">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <h2>Criar conta</h2>
            <small>| Preencha os campos</small>
            <!-- Início do formulário -->
            <form action="/to-do/register" method="post" class="mt-2">
                <!-- Campo Nome -->
                <div class="form-group">
                    <label for="name">Nome:</label>
                    <input type="text" class="form-control" id="name" name="name">
                </div>

                <!-- Campo Sobrenome -->
                <div class="form-group">
                    <label for="lastname">Sobrenome:</label>
                    <input type="text" class="form-control" id="lastname" name="lastname">
                </div>

                <!-- Campo Email -->
                <div class="form-group">
                    <label for="email">Email:</label>
                    <input type="email" class="form-control" id="email" name="email">
                </div>

                <!-- Campo Imagem
                <div class="form-group">
                    <label for="image">Imagem:</label>
                    <input type="file" class="form-control-file" id="image" name="image">
                </div>

                -->
                <!-- Campo Senha -->
                <div class="form-group">
                    <label for="password">Senha:</label>
                    <input type="password" class="form-control" id="password" name="password">
                </div>

                <div class="form-group">
                    <label for="password">Confirme sua senha:</label>
                    <input type="password" class="form-control" id="password" name="confirmpassword">
                </div>

                <!-- Botão de Registro -->
                <button type="submit" class="btn btn-primary full-btn">Registrar</button>
            </form>
            <!-- Fim do formulário -->
            <script type='text/javascript'>toastr.{{type}}('{{msg}}')</script>
        </div>
    </div>
</div>