<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="title">
            <h1>Organize seu trabalho e sua vida.</h1>
            <div style="width: 100%; display: flex; align-items: center; justify-content: center;">
                <h3 style="margin-right: 10px;font-style: italic;">E-Task</h3>
                <small style="align-self: center;">Seu gerenciador de tarefas eletrônico.</small>
            </div>

        </div>
        <div class="options">
            <a href="/to-do/login">Entrar</a>
            <a href="/to-do/register">Registrar</a>
        </div>
    </div>
</div>